repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args:
          - "--unsafe"
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: debug-statements
      -   id: double-quote-string-fixer
      -   id: name-tests-test
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.10
      - id: black-jupyter
        language_version: python3.10

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
