task_name: segmentation

seed: 777
sample_interval: 20

n_epochs: 1000
epoch_steps: 100

logging_dir: ./training_logs/segmentation/tumors-kits-tsm
experiment_name: seg_unet-effb0_iou-focal_aug_split0_mcseg_zeromsk_aux-avgp-nodr_lr2_tm-area-split
checkpoint_freq: 10

dataset:
  kind: merged
  batch_size: 128
  img_size: [256, 256] # hxw
  use_sampler: True
  reset_sampler: True
  num_workers: 28
  imagenet_norm: False # mean=[0.5], std=[0.5]
  root_dir: null
  augs: [hflip, vflip, shift_scale_rotate] # only resize and norm

  datasets:
    - kind: totalsegmentor
      root_dir: ./data/totalsegmentor-v1-controls
      labels_dir: nnUNet_predictions
      # limit_scans: 5

      scan_params:
        load_masks: ['empty', 'kidney', 'tumor']
        min_max_normalization: True
        slicing_direction: axial
        classes: ['empty', 'kidney', 'tumor']

        # fetch only kidney slices in loaders that have masks with at least `filter_class_slices_thresh` non zero pixels
        filter_class_slices: ['kidney']
        filter_class_slices_thresh: 100

        default_label: 0

    - kind: kits
      root_dir: data/kits23
      # split_dir: splits/skf_area_split0
      split_dir: splits/skf_tumor_area_split0

      # limit_scans: 5

      # LABEL_AGGREGATION_ORDER = (1, 3, 2)
      # this means that we first place the kidney, then the cyst and finally the
      # tumor. The order matters! If parts of a later label (example tumor) overlap
      # with a prior label (kidney or cyst) the prior label is overwritten
      # KITS_LABEL_NAMES = {
      #     1: "kidney",
      #     2: "tumor",
      #     3: "cyst"
      # }
      scan_params:
        load_masks: ['empty', 'kidney', 'tumor']
        min_max_normalization: True
        slicing_direction: axial
        classes: ['empty', 'kidney', 'tumor', 'cyst']
        
        sampling_class: ['tumor']
        classify_labels: ['tumor']
        classify_labels_thresh: 32

        # fetch only kidney slices in loaders that have masks with at least `filter_class_slices_thresh` non zero pixels
        filter_class_slices: ['kidney']
        filter_class_slices_thresh: 100

model:
  kind: Unet
  n_classes: &CLASSES 1
  encoder_name: efficientnet-b0
  encoder_weights: imagenet
  restore_ckpt: training_logs/classification/resnet18-October-21-2023_02+35PM-af13228-tsm_synth_r18_kdn-only/checkpoints/checkpoint_50.pth
  in_channels: 1

  segment_mask_ids: [0, 1, 2] # multiclass segmentation of kidneys and tumors
  aux_output: True
  aux_params: 
    pooling: avg # one of 'avg', 'max'
    dropout: null # dropout ratio, default is None
    activation: null 
    classes: *CLASSES

  aux_output_pos: backbone

  loss: bce

  # optimizer's parameters
  lr: 0.0008
  b1: 0.9
  b2: 0.999
  weight_decay: 0.0001
