task_name: segmentation

seed: 777
sample_interval: 30

n_epochs: 1000
epoch_steps: 100

logging_dir: ./training_logs/segmentation/cysts-kits
experiment_name: seg_unet-r18_iou-focal_cyst-only_aug_split0
checkpoint_freq: 10

dataset:
  kind: kits
  root_dir: /tmp/kits23/kits23
  split_dir: splits/skf_area_split0
  batch_size: 128
  img_size: [256, 256] # hxw
  use_sampler: True
  reset_sampler: False
  num_workers: 28
  imagenet_norm: False # mean=[0.5], std=[0.5]
  augs: [hflip, vflip, shift_scale_rotate] # only resize and norm

  # LABEL_AGGREGATION_ORDER = (1, 3, 2)
  # this means that we first place the kidney, then the cyst and finally the
  # tumor. The order matters! If parts of a later label (example tumor) overlap
  # with a prior label (kidney or cyst) the prior label is overwritten
  # KITS_LABEL_NAMES = {
  #     1: "kidney",
  #     2: "tumor",
  #     3: "cyst"
  # }

  scan_params:
    load_masks: True
    min_max_normalization: True
    slicing_direction: axial
    classes: ['empty', 'kidney', 'tumor', 'cyst']
    
    sampling_class: ['cyst']
    classify_labels: ['cyst']
    classify_labels_thresh: 8

    # fetch only kidney slices in loaders that have masks with at least `filter_class_slices_thresh` non zero pixels
    filter_class_slices: ['kidney']
    filter_class_slices_thresh: 32

model:
  kind: Unet
  n_classes: 1
  encoder_name: efficientnet-b0
  encoder_weights: imagenet
  restore_ckpt: training_logs/classification/resnet18-October-21-2023_02+35PM-af13228-tsm_synth_r18_kdn-only/checkpoints/checkpoint_50.pth
  in_channels: 1

  segment_mask_ids: [1] # binary segmentation of kidneys
  aux_output: True

  loss: bce

  # optimizer's parameters
  lr: 0.001
  b1: 0.9
  b2: 0.999
  weight_decay: 0.0001
