task_name: counterfactual

seed: 777
sample_interval: 30

n_epochs: 1000

logging_dir: './training_logs'
checkpoint_freq: 5

dataset:
  root_dir: ./COVID-19_Radiography_Dataset_v2/
  annotations:
    # specify training set as the classifier's validation one and vice versa
    train: classifier_validation.csv
    val: explanator_val.csv
  batch_size: 2
  img_size: [256, 256] # hxw
  use_sampler: True
  num_workers: 4
  imagenet_norm: False # mean=[0.5], std=[0.5]
  augs: [] # only resize and norm

model:
  kind: counterfactual_lungs_cgan
  in_channels: 1
  gen_update_freq: 5
  lambda_adv: 1.0
  # lambda_kl: 0.05
  lambda_kl: 1.0
  lambda_rec: 6

  # counterfactual parameters
  num_bins: 2 # number of discrete bins into which posterior probabilities are sorted
  explain_class_idx: 0 # normal lungs

  # classifier parameters
  n_classes: 4 # number of classes in the classifier
  classifier_ckpt: ./saved_models/resnet18_multiclass_pretrain.pth

  # optimizers' parameters
  lr: 0.0002
  b1: 0.0
  b2: 0.999
