task_name: counterfactual

seed: 777
sample_interval: 50

n_epochs: 1000
# epoch_steps: 800

logging_dir: ./training_logs/counterfactual
experiment_name: tsm_synth-large_r18_e2e_kdn-only_bs32_gsp_arch2_advhinge_fixcomp_bce
checkpoint_freq: 5
eval_counter_freq: 2

compute_norms: True

dataset:
  kind: totalsegmentor
  root_dir: ./data/totalsegmentor # 1804 * 64 slices in totalsegmentor dataset
  batch_size: 32
  img_size: [256, 256] # hxw
  use_sampler: False
  num_workers: 28
  imagenet_norm: False # mean=[0.5], std=[0.5]
  augs: [] # only resize and norm

  # limit_scans: 10
  scan_params:
    load_masks: True
    min_max_normalization: True
    slicing_direction: axial
    classes: ['empty', 'kidney']
    sampling_class: ['kidney']
    filter_class_slices: ['kidney']
    filter_class_slices_thresh: 32

    synth_params:
      p: 0.65
      size: 20
      sigma: 0.4
      mask_thresh: 0.25

model:
  kind: counterfactual_lungs_cgan
  in_channels: 1
  gen_update_freq: 5
  adv_loss: bce
  lambda_adv: 1.0
  # lambda_kl: 0.05
  lambda_kl: 0.01
  lambda_rec: 1.0
  lambda_minc: 0

  # default setting
  enc_params:
    downsample_scales: [2, 4, 8, 16, 32]
    out_channels: [64, 128, 256, 512, 1024]

  gen_params:
    upsample_scales: [2, 2, 2, 2, 2]
    out_channels: [1024, 512, 256, 128, 64]

  disc_params:
    downsample_scales: [2, 4, 8, 16, 32, 32]
    out_channels: [64, 128, 256, 512, 1024, 1024]

  # counterfactual parameters
  num_bins: 2 # number of discrete bins into which posterior probabilities are sorted
  explain_class_idx: 0 # normal/not-normal kidneys

  # classifier parameters
  classifier_kind: resnet18
  n_classes: 1 # number of classes in the classifier
  classifier_ckpt: training_logs/classification/resnet18-November-17-2023_06+43PM-df986d6-tsm_synth-large_r18_aug/checkpoints/checkpoint_16.pth

  # optimizers' parameters
  lr: 0.0002
  b1: 0.0
  b2: 0.999
