task_name: counterfactual

seed: 777
sample_interval: 30

n_epochs: 1000
epoch_steps: 800

logging_dir: ./training_logs/counterfactual
experiment_name: tsm_synth_r18_e2e
checkpoint_freq: 5
eval_counter_freq: 10

dataset:
  kind: totalsegmentor
  root_dir: /tmp/totalsegmentor # 1804 * 64 slices in totalsegmentor dataset
  batch_size: 16
  img_size: [256, 256] # hxw
  use_sampler: True
  num_workers: 28
  imagenet_norm: False # mean=[0.5], std=[0.5]
  augs: [] # only resize and norm

  scan_params:
    min_max_normalization: True
    slicing_direction: axial
    classes: ['empty', 'kidney']
    sampling_class: kidney
    load_masks: True
    synth_params:
      p: 0.8
      size: 8
      sigma: 0.5

model:
  kind: counterfactual_lungs_cgan
  in_channels: 1
  gen_update_freq: 5
  lambda_adv: 1.0
  # lambda_kl: 0.05
  lambda_kl: 1.0
  lambda_rec: 6

  # counterfactual parameters
  num_bins: 2 # number of discrete bins into which posterior probabilities are sorted
  explain_class_idx: 0 # normal/not-normal kidneys

  # classifier parameters
  classifier_kind: resnet18
  n_classes: 1 # number of classes in the classifier
  classifier_ckpt: training_logs/classification/resnet18-October-14-2023_01+03PM-af13228-tsm_synth_r18/checkpoints/checkpoint_55.pth

  # optimizers' parameters
  lr: 0.0002
  b1: 0.0
  b2: 0.999
