task_name: classification

seed: 777
sample_interval: 30

n_epochs: 1000

logging_dir: ./training_logs/classification/cysts
experiment_name: tsm_synth_r50_cyst-only_aug_cf_split2
checkpoint_freq: 10

dataset:
  kind: totalsegmentor
  version: 2
  root_dir: ./data/totalsegmentor-v2
  labels_dir: original-labels
  batch_size: 128
  img_size: [256, 256] # hxw
  use_sampler: True
  reset_sampler: True
  num_workers: 28
  imagenet_norm: False # mean=[0.5], std=[0.5]
  augs: [hflip, vflip, shift_scale_rotate] # only resize and norm

  scan_params:
    # load_masks: True
    min_max_normalization: True
    slicing_direction: axial
    classes: ['empty', 'kidney_left', 'kidney_cyst_left', 'kidney_right', 'kidney_cyst_right']
    sampling_class: ['kidney_cyst_left', 'kidney_cyst_right']
    # fetch only kidney slices in loaders
    classify_labels: ['kidney_cyst_left', 'kidney_cyst_right']
    classify_labels_thresh: 4

    # fetch only kidney slices in loaders that have masks with at least `filter_class_slices_thresh` non zero pixels
    filter_class_slices: ['kidney_left', 'kidney_right']
    filter_class_slices_thresh: 32

model:
  kind: resnet50
  n_classes: 1
  pretrained: True
  restore_ckpt: null
  in_channels: 1

  loss: bce

  # optimizer's parameters
  lr: 0.001
  b1: 0.9
  b2: 0.999
