task_name: classification

seed: 777
sample_interval: 30

n_epochs: 1000

logging_dir: ./training_logs/classification/cysts
experiment_name: tsm_synth_r18_cyst-only
checkpoint_freq: 10

dataset:
  kind: totalsegmentor
  version: 1
  root_dir: data/totalsegmentor # 1804 * 64 slices in totalsegmentor dataset
  batch_size: 64
  img_size: [256, 256] # hxw
  use_sampler: True
  reset_sampler: True
  num_workers: 0
  imagenet_norm: False # mean=[0.5], std=[0.5]
  augs: [] # only resize and norm

  scan_params:
    load_masks: True
    min_max_normalization: True
    slicing_direction: axial
    sampling_class: ['kidney_cyst']
    classify_labels: ['kidney_cyst']
    classes: ['empty', 'kidney', 'kidney_tumor', 'kidney_cyst']
    filter_class_slices: ['kidney'] # fetch only kidney slices in loaders

model:
  kind: resnet18
  n_classes: 1
  pretrained: True
  restore_ckpt: null
  in_channels: 1

  loss: bce

  # optimizer's parameters
  lr: 0.001
  b1: 0.9
  b2: 0.999
