seed: 777
sample_interval: 30

n_epochs: 30

model_dir: './training_logs/lungs_cgan'
dataset:
  root_dir: ./COVID-19_Radiography_Dataset_v2/
  annotations:
    # train: train.csv
    # val: val.csv
    train: val.csv # FIXME
    val: train.csv # FIXME
  batch_size: 16
  img_size: [256, 256] # hxw
  use_sampler: True
  num_workers: 4
  imagenet_norm: False # mean=[0.5], std=[0.5]
  augs: [] # only resize and norm

model:
  n_classes: 4
  in_channels: 1
  lr: 0.0002
  b1: 0.0
  b2: 0.999
